### ISSUE TITLE
TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by kurtextrem** [capaj/vscode-exports-autocomplete#35]
Cannot match against 'undefined' or 'null'.: TypeError: Cannot match against 'undefined' or 'null'.
    at fs.readFile (C:\Users\admin\.vscode-insiders\extensions\capaj.vscode-exports-autocomplete-0.4.9\lib\uses-semi.js:11:38)
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)

**Comment by capaj** [comment]
fixed in 0.5.0
