### ISSUE TITLE
Cannot match against 'undefined' or 'null'.:

### ISSUE THREAD

**Issue by cjhoward92** [capaj/vscode-exports-autocomplete#41]
I am getting this in the Developer Console, version 0.5.1

```javascript
[capaj.vscode-exports-autocomplete] Cannot match against 'undefined' or 'null'.: TypeError: Cannot match against 'undefined' or 'null'.
	at workspace.onDidChangeTextDocument (C:\Users\carsonh\.vscode\extensions\capaj.vscode-exports-autocomplete-0.5.1\lib\add-import-on-paste.js:30:45)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:55287)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57078)
	at e.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:348716)
	at e.$acceptModelSaved (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:348499)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423958)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:280244)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:279271
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:281190
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:56058
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:55287)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57078)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:102495)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
```

It was fine for a while, stopped working recently (maybe a few days ago?)

**Comment by capaj** [comment]
fixed by 21e27039, released as 0.5.2
